### ISSUE TITLE
관리자 페이지

### ISSUE THREAD

**Issue by iamidlek** [imhaeunk/Team_mini#20]
[  ] 좌측 상단에 관리자 정보, 좌측 하단에 판매내역, 제품 조회 라우터 링크 구현
[  ] 판매내역을 누르면 관리자 페이지 중앙에 보인다
[  ] 제품 조회를 누르면 관리자 페이지 중앙에 보인다
[  ] 제품 추가 버튼을 누르면 제품 추가 페이지로 이동
[  ] 제품 내역에서 제품 수정을 누르면 해당 제품에 대한 정보를 수정할 수 있는 페이지로 이동

**Comment by imparang** [comment]
처음에 관리자 페이지로 접근했을 때, 판매내역과 제품 조회 중 어떤 것이 먼저 보이면 좋을까요?

**Comment by iamidlek** [comment]
지금 fetch 해서 로컬에서 돌려보시면
전 제품 조회가 먼저 나오는 구조입니다!
(어느쪽도 괜찮다고 생각하지만)
초반 회의 내용대로 구현되어있습니다!

**Comment by iamidlek** [comment]
[ 추가 ]
하은님과 동수님 코드 봐드리면서
처음 정한 

왼쪽에 로우터 링크가 보이는 상태 유지 되면서

가운데에 목록이 보여주고 수정, 제품 자세히 보기 도 동일한 틀 내에서 보여지는 
방식으로 작성해 주신걸로 압니다!

**Comment by imparang** [comment]
감사합니당
